// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/task.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/task.go -destination=internal/repository/mocks/task_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dto "todo-list/internal/dto"
	model "todo-list/internal/model"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskRepositoryI is a mock of TaskRepositoryI interface.
type MockTaskRepositoryI struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryIMockRecorder
	isgomock struct{}
}

// MockTaskRepositoryIMockRecorder is the mock recorder for MockTaskRepositoryI.
type MockTaskRepositoryIMockRecorder struct {
	mock *MockTaskRepositoryI
}

// NewMockTaskRepositoryI creates a new mock instance.
func NewMockTaskRepositoryI(ctrl *gomock.Controller) *MockTaskRepositoryI {
	mock := &MockTaskRepositoryI{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepositoryI) EXPECT() *MockTaskRepositoryIMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskRepositoryI) CreateTask(arg0 context.Context, arg1 dto.CreateTaskTodoRequest, arg2 uint) (*model.TaskTodos, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.TaskTodos)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskRepositoryIMockRecorder) CreateTask(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskRepositoryI)(nil).CreateTask), arg0, arg1, arg2)
}

// UpdateStatusTask mocks base method.
func (m *MockTaskRepositoryI) UpdateStatusTask(arg0 context.Context, arg1 dto.UpdateStatusTaskTodoRequest, arg2, arg3 uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusTask", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatusTask indicates an expected call of UpdateStatusTask.
func (mr *MockTaskRepositoryIMockRecorder) UpdateStatusTask(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusTask", reflect.TypeOf((*MockTaskRepositoryI)(nil).UpdateStatusTask), arg0, arg1, arg2, arg3)
}
