// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/todo.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/todo.go -destination=internal/repository/mocks/todo_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "todo-list/internal/model"

	gomock "go.uber.org/mock/gomock"
)

// MockTodoRepositoryI is a mock of TodoRepositoryI interface.
type MockTodoRepositoryI struct {
	ctrl     *gomock.Controller
	recorder *MockTodoRepositoryIMockRecorder
	isgomock struct{}
}

// MockTodoRepositoryIMockRecorder is the mock recorder for MockTodoRepositoryI.
type MockTodoRepositoryIMockRecorder struct {
	mock *MockTodoRepositoryI
}

// NewMockTodoRepositoryI creates a new mock instance.
func NewMockTodoRepositoryI(ctrl *gomock.Controller) *MockTodoRepositoryI {
	mock := &MockTodoRepositoryI{ctrl: ctrl}
	mock.recorder = &MockTodoRepositoryIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoRepositoryI) EXPECT() *MockTodoRepositoryIMockRecorder {
	return m.recorder
}

// CreateTodo mocks base method.
func (m *MockTodoRepositoryI) CreateTodo(arg0 context.Context, arg1 *model.Todo) (*model.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTodo", arg0, arg1)
	ret0, _ := ret[0].(*model.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTodo indicates an expected call of CreateTodo.
func (mr *MockTodoRepositoryIMockRecorder) CreateTodo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTodo", reflect.TypeOf((*MockTodoRepositoryI)(nil).CreateTodo), arg0, arg1)
}

// DeleteTodo mocks base method.
func (m *MockTodoRepositoryI) DeleteTodo(arg0 context.Context, arg1, arg2 uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTodo", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTodo indicates an expected call of DeleteTodo.
func (mr *MockTodoRepositoryIMockRecorder) DeleteTodo(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTodo", reflect.TypeOf((*MockTodoRepositoryI)(nil).DeleteTodo), arg0, arg1, arg2)
}

// GetTodoById mocks base method.
func (m *MockTodoRepositoryI) GetTodoById(arg0 context.Context, arg1 uint) (*model.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodoById", arg0, arg1)
	ret0, _ := ret[0].(*model.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodoById indicates an expected call of GetTodoById.
func (mr *MockTodoRepositoryIMockRecorder) GetTodoById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodoById", reflect.TypeOf((*MockTodoRepositoryI)(nil).GetTodoById), arg0, arg1)
}

// ListTodos mocks base method.
func (m *MockTodoRepositoryI) ListTodos(arg0 context.Context, arg1 uint, arg2, arg3 int) ([]*model.Todo, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTodos", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*model.Todo)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTodos indicates an expected call of ListTodos.
func (mr *MockTodoRepositoryIMockRecorder) ListTodos(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTodos", reflect.TypeOf((*MockTodoRepositoryI)(nil).ListTodos), arg0, arg1, arg2, arg3)
}

// UpdateTodo mocks base method.
func (m *MockTodoRepositoryI) UpdateTodo(arg0 context.Context, arg1 *model.Todo) (*model.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodo", arg0, arg1)
	ret0, _ := ret[0].(*model.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTodo indicates an expected call of UpdateTodo.
func (mr *MockTodoRepositoryIMockRecorder) UpdateTodo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodo", reflect.TypeOf((*MockTodoRepositoryI)(nil).UpdateTodo), arg0, arg1)
}
