CREATE TABLE IF NOT EXISTS task_todos (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    todo_id INTEGER NOT NULL,
    status BOOLEAN NOT NULL DEFAULT FALSE,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY (todo_id) REFERENCES todos(id) ON DELETE CASCADE
);

