// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/task-service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/task-service.go -destination=internal/service/mocks/task_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dto "todo-list/internal/dto"
	model "todo-list/internal/model"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskServiceI is a mock of TaskServiceI interface.
type MockTaskServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockTaskServiceIMockRecorder
	isgomock struct{}
}

// MockTaskServiceIMockRecorder is the mock recorder for MockTaskServiceI.
type MockTaskServiceIMockRecorder struct {
	mock *MockTaskServiceI
}

// NewMockTaskServiceI creates a new mock instance.
func NewMockTaskServiceI(ctrl *gomock.Controller) *MockTaskServiceI {
	mock := &MockTaskServiceI{ctrl: ctrl}
	mock.recorder = &MockTaskServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskServiceI) EXPECT() *MockTaskServiceIMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskServiceI) CreateTask(arg0 context.Context, arg1 dto.CreateTaskTodoRequest, arg2 uint) (*model.TaskTodos, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.TaskTodos)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskServiceIMockRecorder) CreateTask(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskServiceI)(nil).CreateTask), arg0, arg1, arg2)
}

// UpdateStatusTask mocks base method.
func (m *MockTaskServiceI) UpdateStatusTask(arg0 context.Context, arg1 dto.UpdateStatusTaskTodoRequest, arg2, arg3 uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusTask", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatusTask indicates an expected call of UpdateStatusTask.
func (mr *MockTaskServiceIMockRecorder) UpdateStatusTask(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusTask", reflect.TypeOf((*MockTaskServiceI)(nil).UpdateStatusTask), arg0, arg1, arg2, arg3)
}
