// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/todo-service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/todo-service.go -destination=internal/service/mocks/todo_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dto "todo-list/internal/dto"
	model "todo-list/internal/model"

	gomock "go.uber.org/mock/gomock"
)

// MockTodoServiceI is a mock of TodoServiceI interface.
type MockTodoServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockTodoServiceIMockRecorder
	isgomock struct{}
}

// MockTodoServiceIMockRecorder is the mock recorder for MockTodoServiceI.
type MockTodoServiceIMockRecorder struct {
	mock *MockTodoServiceI
}

// NewMockTodoServiceI creates a new mock instance.
func NewMockTodoServiceI(ctrl *gomock.Controller) *MockTodoServiceI {
	mock := &MockTodoServiceI{ctrl: ctrl}
	mock.recorder = &MockTodoServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoServiceI) EXPECT() *MockTodoServiceIMockRecorder {
	return m.recorder
}

// CreateTodo mocks base method.
func (m *MockTodoServiceI) CreateTodo(arg0 context.Context, arg1 dto.CreateTodoRequest) (*model.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTodo", arg0, arg1)
	ret0, _ := ret[0].(*model.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTodo indicates an expected call of CreateTodo.
func (mr *MockTodoServiceIMockRecorder) CreateTodo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTodo", reflect.TypeOf((*MockTodoServiceI)(nil).CreateTodo), arg0, arg1)
}

// DeleteTodo mocks base method.
func (m *MockTodoServiceI) DeleteTodo(arg0 context.Context, arg1, arg2 uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTodo", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTodo indicates an expected call of DeleteTodo.
func (mr *MockTodoServiceIMockRecorder) DeleteTodo(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTodo", reflect.TypeOf((*MockTodoServiceI)(nil).DeleteTodo), arg0, arg1, arg2)
}

// GetTodoById mocks base method.
func (m *MockTodoServiceI) GetTodoById(arg0 context.Context, arg1 uint) (*model.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodoById", arg0, arg1)
	ret0, _ := ret[0].(*model.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodoById indicates an expected call of GetTodoById.
func (mr *MockTodoServiceIMockRecorder) GetTodoById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodoById", reflect.TypeOf((*MockTodoServiceI)(nil).GetTodoById), arg0, arg1)
}

// ListTodos mocks base method.
func (m *MockTodoServiceI) ListTodos(arg0 context.Context, arg1 uint, arg2, arg3 int) ([]*model.Todo, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTodos", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*model.Todo)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTodos indicates an expected call of ListTodos.
func (mr *MockTodoServiceIMockRecorder) ListTodos(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTodos", reflect.TypeOf((*MockTodoServiceI)(nil).ListTodos), arg0, arg1, arg2, arg3)
}

// UpdateTodo mocks base method.
func (m *MockTodoServiceI) UpdateTodo(arg0 context.Context, arg1 dto.UpdateTodoRequest, arg2 uint) (*model.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodo", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTodo indicates an expected call of UpdateTodo.
func (mr *MockTodoServiceIMockRecorder) UpdateTodo(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodo", reflect.TypeOf((*MockTodoServiceI)(nil).UpdateTodo), arg0, arg1, arg2)
}
